### PR TITLE
added example of application on readme

### PR DESCRIPTION
**Pull request by LucasBadico**
as discused on #90

### CODE REVIEW

**Comment by jeskew** [comment]
Thanks for putting this together. None of the failure in Travis appear related -- they seem like a Jest instantiation bug, and I'll investigate further.

**Comment by LucasBadico** [comment]
Hey guys, I was, and still with a bunch of things on work, even missed that the build was failling. Can we merge this?

**Comment by jeskew** [comment]
Could this be moved to the repository's top-level readme? The expression builder package is designed to be useful as a standalone tool (not just in the context of the data mapper).

**Comment by LucasBadico** [comment]
I will do that!

**Comment by LucasBadico** [comment]
@jeskew sorry, I have foget about this PR. Just moved. Take a look if I have put in the rigth place.

**Pull request merged**
